//! # Tool Trait, Registry, WASM Sandbox & Execution Pipeline
//!
//! Corresponds to: `src/tools/tool.rs` + `src/tools/execute.rs` + `src/wasm/sandbox.rs`
//!
//! THIS IS THE KEY DIFFERENCE from mini-agent-loop.
//!
//! In mini-agent-loop: Tool trait → native Rust execute()
//! Here:              Tool trait → WasmTool → Wasmtime sandbox → guest .wasm
//!
//! The execution pipeline becomes:
//!   1. LLM returns tool_call(calculator, params)
//!   2. execute_tool_with_safety() looks up the tool
//!   3. WasmTool::execute() creates a fresh WASM Store
//!   4. Guest .wasm runs in sandbox with fuel limit
//!   5. Guest can ONLY call host::log() and host::now_millis()
//!   6. Result comes back through the WIT interface

use async_trait::async_trait;
use serde::{Deserialize, Serialize};
use std::sync::Arc;
use std::time::{Duration, SystemTime, UNIX_EPOCH};

use tracing::{debug, info, trace, warn, error};

use wasmtime::component::Linker;
use wasmtime::{Config, Engine, Store};
use wasmtime_wasi::{ResourceTable, WasiCtx, WasiCtxBuilder, WasiView};

use crate::llm::{ChatMessage, ToolDefinition};

// ============================================================================
// Tool Trait & Registry
// ============================================================================

/// Output from a tool execution.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolOutput {
    pub result: serde_json::Value,
}

/// Trait for tools that the agent can use.
/// Both native and WASM tools implement this trait.
#[async_trait]
pub trait Tool: Send + Sync {
    fn name(&self) -> &str;
    fn description(&self) -> &str;
    fn parameters_schema(&self) -> serde_json::Value;
    async fn execute(&self, params: serde_json::Value) -> Result<ToolOutput, String>;
}

/// Tool registry — holds all available tools.
#[derive(Default)]
pub struct ToolRegistry {
    tools: Vec<Box<dyn Tool>>,
}

impl ToolRegistry {
    pub fn new() -> Self {
        debug!("Creating new ToolRegistry");
        Self { tools: Vec::new() }
    }

    pub fn register(&mut self, tool: Box<dyn Tool>) {
        info!(tool_name = %tool.name(), "Registering tool: '{}'", tool.name());
        debug!(
            tool_name = %tool.name(),
            description = %tool.description(),
            schema = %serde_json::to_string_pretty(&tool.parameters_schema()).unwrap_or_default(),
            "Tool details"
        );
        self.tools.push(tool);
    }

    pub fn get(&self, name: &str) -> Option<&dyn Tool> {
        self.tools
            .iter()
            .find(|t| t.name() == name)
            .map(|t| t.as_ref())
    }

    pub fn definitions(&self) -> Vec<ToolDefinition> {
        self.tools
            .iter()
            .map(|t| ToolDefinition {
                name: t.name().to_string(),
                description: t.description().to_string(),
                parameters: t.parameters_schema(),
            })
            .collect()
    }
}

// ════════════════════════════════════════════════════════════════════
// WASM Sandbox Infrastructure
// ════════════════════════════════════════════════════════════════════
// This section implements the WASM sandbox that tools run inside.
//
// Key components:
//   1. WIT bindings (generated by wasmtime::component::bindgen!)
//   2. StoreData — per-execution state (logs, WASI context)
//   3. Host trait impl — what the guest can call (log, now_millis)
//   4. WasmToolEngine — shared engine + compiled component
//   5. WasmTool — implements Tool trait using the sandbox
// ════════════════════════════════════════════════════════════════════

// Step 1: Generate host-side bindings from the WIT file.
//
// This macro reads the WIT and generates:
//   - `demo::sandbox::host::Host` trait (we must implement)
//   - `demo::sandbox::host::add_to_linker()` function
//   - `SandboxedTool` struct with `instantiate()` to create guest instances
//   - `exports::demo::sandbox::tool::*` types for calling guest functions
wasmtime::component::bindgen!({
    path: "../wit/tool.wit",
    world: "sandboxed-tool",
    async: false,
    with: {},
});

// Step 2: Per-execution state.
//
// Each tool execution gets a FRESH Store — this is the "fresh instance
// per execution" pattern, ensuring complete isolation between runs.
// No state leaks from one execution to the next.
struct StoreData {
    wasi: WasiCtx,
    table: ResourceTable,
    /// Collected log messages from the guest
    logs: Vec<(String, String)>,
}

impl WasiView for StoreData {
    fn ctx(&mut self) -> &mut WasiCtx {
        &mut self.wasi
    }
    fn table(&mut self) -> &mut ResourceTable {
        &mut self.table
    }
}

// Step 3: Implement the Host trait — THE CORE OF THE SANDBOX.
//
// When the guest calls `host::log(...)` or `host::now_millis()`,
// execution crosses the WASM boundary and arrives HERE.
//
// The host has FULL CONTROL over what these functions do:
// - log() could write to a file, send to a server, or just collect in memory
// - now_millis() could return the real time, or a fake time for testing
// - In IronClaw, http_request() checks an allowlist before making the request
//
// The guest has NO WAY to bypass this — it's enforced by the WASM VM.
impl demo::sandbox::host::Host for StoreData {
    fn log(&mut self, level: demo::sandbox::host::LogLevel, message: String) {
        let level_str = match level {
            demo::sandbox::host::LogLevel::Info => "INFO",
            demo::sandbox::host::LogLevel::Warn => "WARN",
            demo::sandbox::host::LogLevel::Error => "ERROR",
        };
        info!(
            wasm_log_level = %level_str,
            wasm_message = %message,
            "📋 [WASM LOG] [{}] {}", level_str, message
        );
        println!("    📋 [WASM LOG] [{level_str}] {message}");
        self.logs.push((level_str.to_string(), message));
    }

    fn now_millis(&mut self) -> u64 {
        let millis = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map(|d| d.as_millis() as u64)
            .unwrap_or(0);
        trace!(millis = millis, "WASM guest called now_millis()");
        millis
    }
}

// Step 4: Shared WASM engine + compiled component.
//
// The Engine and compiled Component are expensive to create but can be
// reused across executions. Only the Store (per-execution state) is fresh.
pub struct WasmToolEngine {
    engine: Engine,
    component: wasmtime::component::Component,
    /// Tool metadata (cached from first instantiation)
    pub tool_name: String,
    pub tool_description: String,
    pub tool_schema: serde_json::Value,
    /// Fuel limit per execution
    pub fuel_limit: u64,
}

impl WasmToolEngine {
    /// Create a new WASM tool engine from a .wasm file.
    ///
    /// This:
    /// 1. Creates a Wasmtime engine with component model + fuel metering
    /// 2. Compiles the WASM bytes to native code
    /// 3. Instantiates once to read tool metadata (name, description, schema)
    pub fn new(wasm_path: &str, fuel_limit: u64) -> Result<Self, String> {
        info!(
            wasm_path = %wasm_path,
            fuel_limit = fuel_limit,
            "🔧 Creating WASM tool engine"
        );
        // Create engine with component model and fuel metering
        let mut config = Config::new();
        config.wasm_component_model(true);
        config.consume_fuel(true);
        let engine =
            Engine::new(&config).map_err(|e| format!("Failed to create WASM engine: {}", e))?;

        // Load and compile the WASM component
        debug!(wasm_path = %wasm_path, "Loading WASM bytes from file");
        let wasm_bytes = std::fs::read(wasm_path)
            .map_err(|e| format!("Failed to read WASM file '{}': {}", wasm_path, e))?;
        info!(wasm_size = wasm_bytes.len(), "WASM file loaded ({} bytes)", wasm_bytes.len());

        debug!("Compiling WASM component...");
        let component = wasmtime::component::Component::new(&engine, &wasm_bytes)
            .map_err(|e| format!("Failed to compile WASM component: {}", e))?;
        info!("✅ WASM component compiled successfully");

        // Instantiate once to read metadata
        debug!("Instantiating WASM component to read metadata...");
        let mut linker: Linker<StoreData> = Linker::new(&engine);
        wasmtime_wasi::add_to_linker_sync(&mut linker)
            .map_err(|e| format!("Failed to add WASI to linker: {}", e))?;
        demo::sandbox::host::add_to_linker(&mut linker, |state| state)
            .map_err(|e| format!("Failed to add host functions to linker: {}", e))?;

        let mut store = Store::new(
            &engine,
            StoreData {
                wasi: WasiCtxBuilder::new().build(),
                table: ResourceTable::new(),
                logs: Vec::new(),
            },
        );
        store
            .set_fuel(fuel_limit)
            .map_err(|e| format!("Failed to set fuel: {}", e))?;

        let instance = SandboxedTool::instantiate(&mut store, &component, &linker)
            .map_err(|e| format!("Failed to instantiate WASM tool: {}", e))?;

        // Read tool metadata from the guest itself (name comes from guest, not caller)
        let tool_name = instance
            .demo_sandbox_tool()
            .call_name(&mut store)
            .map_err(|e| format!("Failed to call name(): {}", e))?;
        let description = instance
            .demo_sandbox_tool()
            .call_description(&mut store)
            .map_err(|e| format!("Failed to call description(): {}", e))?;
        let schema_str = instance
            .demo_sandbox_tool()
            .call_schema(&mut store)
            .map_err(|e| format!("Failed to call schema(): {}", e))?;
        let schema: serde_json::Value = serde_json::from_str(&schema_str)
            .map_err(|e| format!("Failed to parse schema JSON: {}", e))?;

        info!(
            tool_name = %tool_name,
            tool_description = %description,
            "✅ WASM tool metadata loaded: name='{}'", tool_name
        );
        debug!(
            tool_schema = %serde_json::to_string_pretty(&schema).unwrap_or_default(),
            "WASM tool schema"
        );

        Ok(Self {
            engine,
            component,
            tool_name,
            tool_description: description,
            tool_schema: schema,
            fuel_limit,
        })
    }

    /// Execute the tool in a fresh sandbox.
    ///
    /// Each call creates a NEW Store — complete isolation between executions.
    /// The guest gets a fresh fuel budget and clean state every time.
    fn execute_in_sandbox(&self, params: &str) -> Result<String, String> {
        info!(
            tool = %self.tool_name,
            params = %params,
            fuel_limit = self.fuel_limit,
            "🏖️  Executing tool in WASM sandbox"
        );
        // Fresh linker for this execution
        let mut linker: Linker<StoreData> = Linker::new(&self.engine);
        wasmtime_wasi::add_to_linker_sync(&mut linker)
            .map_err(|e| format!("WASI linker error: {}", e))?;
        demo::sandbox::host::add_to_linker(&mut linker, |state| state)
            .map_err(|e| format!("Host linker error: {}", e))?;

        // Fresh store — complete isolation from previous executions
        debug!("Creating fresh WASM store (complete isolation)");
        let mut store = Store::new(
            &self.engine,
            StoreData {
                wasi: WasiCtxBuilder::new().build(),
                table: ResourceTable::new(),
                logs: Vec::new(),
            },
        );
        store
            .set_fuel(self.fuel_limit)
            .map_err(|e| format!("Fuel error: {}", e))?;

        // Instantiate the guest in the sandbox
        debug!("Instantiating WASM guest in sandbox...");
        let instance = SandboxedTool::instantiate(&mut store, &self.component, &linker)
            .map_err(|e| format!("Instantiation error: {}", e))?;

        // Call the guest's execute() function
        info!("📤 Calling WASM guest execute() function");
        let request = exports::demo::sandbox::tool::Request {
            params: params.to_string(),
        };
        let response = instance
            .demo_sandbox_tool()
            .call_execute(&mut store, &request)
            .map_err(|e| format!("WASM execution error: {}", e))?;

        // Report fuel consumption
        let remaining = store.get_fuel().unwrap_or(0);
        let consumed = self.fuel_limit - remaining;
        info!(
            fuel_consumed = consumed,
            fuel_remaining = remaining,
            fuel_limit = self.fuel_limit,
            "⛽ Fuel consumed: {} / {} units", consumed, self.fuel_limit
        );
        println!(
            "    ⛽ Fuel consumed: {} / {} units",
            consumed, self.fuel_limit
        );

        // Collect guest logs
        let guest_logs = &store.data().logs;
        if !guest_logs.is_empty() {
            debug!(
                log_count = guest_logs.len(),
                "WASM guest produced {} log message(s)", guest_logs.len()
            );
            for (level, msg) in guest_logs {
                trace!(wasm_log_level = %level, wasm_log_msg = %msg, "Guest log: [{}] {}", level, msg);
            }
        }

        // Check response
        if let Some(error) = response.error {
            error!(error = %error, "WASM tool returned error");
            return Err(format!("Tool error: {}", error));
        }
        let output = response
            .output
            .ok_or_else(|| "Tool returned no output".to_string())?;
        info!(output_len = output.len(), "✅ WASM tool execution succeeded ({} chars output)", output.len());
        debug!(output = %output, "Full WASM tool output");
        Ok(output)
    }
}

// Step 5: WasmTool — implements the Tool trait using the WASM sandbox.
//
// This is the bridge between the agent loop's Tool abstraction and
// the WASM sandbox execution. The agent loop doesn't know or care
// that the tool runs in a sandbox — it just calls execute().
pub struct WasmTool {
    pub engine: Arc<WasmToolEngine>,
}

#[async_trait]
impl Tool for WasmTool {
    fn name(&self) -> &str {
        &self.engine.tool_name
    }

    fn description(&self) -> &str {
        &self.engine.tool_description
    }

    fn parameters_schema(&self) -> serde_json::Value {
        self.engine.tool_schema.clone()
    }

    async fn execute(&self, params: serde_json::Value) -> Result<ToolOutput, String> {
        let params_str = serde_json::to_string(&params)
            .map_err(|e| format!("Failed to serialize params: {}", e))?;

        info!(
            tool = %self.engine.tool_name,
            params = %params_str,
            "🔧 WasmTool::execute() — dispatching to WASM sandbox"
        );

        // Execute in WASM sandbox (synchronous — WASM execution is sync)
        // We use spawn_blocking to avoid blocking the async runtime
        let engine = self.engine.clone();
        let exec_start = std::time::Instant::now();
        let result = tokio::task::spawn_blocking(move || engine.execute_in_sandbox(&params_str))
            .await
            .map_err(|e| format!("Task join error: {}", e))??;
        let exec_elapsed = exec_start.elapsed();

        info!(
            elapsed_ms = exec_elapsed.as_millis(),
            "WASM sandbox execution completed in {}ms", exec_elapsed.as_millis()
        );

        // Parse the JSON output from the guest
        let value: serde_json::Value = serde_json::from_str(&result)
            .map_err(|e| format!("Failed to parse tool output: {}", e))?;

        Ok(ToolOutput { result: value })
    }
}

// ════════════════════════════════════════════════════════════════════
// Tool Execution Pipeline
// ════════════════════════════════════════════════════════════════════

/// Execute a tool with timeout.
/// Maps to: `src/tools/execute.rs` → `execute_tool_with_safety()`
pub async fn execute_tool_with_safety(
    registry: &ToolRegistry,
    tool_name: &str,
    params: serde_json::Value,
) -> Result<String, String> {
    info!(tool = %tool_name, "🔍 Looking up tool in registry");

    let tool = registry
        .get(tool_name)
        .ok_or_else(|| {
            error!(tool = %tool_name, "Tool '{}' not found in registry", tool_name);
            format!("Tool '{}' not found", tool_name)
        })?;

    debug!(
        tool = %tool_name,
        params = %serde_json::to_string_pretty(&params).unwrap_or_default(),
        "Tool found, preparing execution"
    );
    println!(
        "  ⚙️  Executing tool: {} with params: {}",
        tool_name, params
    );

    let timeout = Duration::from_secs(30);
    info!(
        tool = %tool_name,
        timeout_secs = 30,
        "⏱️  Executing tool with {}s timeout",
        30
    );

    let exec_start = std::time::Instant::now();
    let result = tokio::time::timeout(timeout, tool.execute(params)).await;
    let exec_elapsed = exec_start.elapsed();

    match result {
        Ok(Ok(output)) => {
            info!(
                tool = %tool_name,
                elapsed_ms = exec_elapsed.as_millis(),
                "✅ Tool execution succeeded in {}ms",
                exec_elapsed.as_millis()
            );
            trace!(
                tool = %tool_name,
                raw_output = %serde_json::to_string_pretty(&output.result).unwrap_or_default(),
                "Raw tool output"
            );
            let serialized = serde_json::to_string_pretty(&output.result)
                .map_err(|e| {
                    error!(error = %e, "Failed to serialize tool result");
                    format!("Failed to serialize result: {}", e)
                })?;
            debug!(
                tool = %tool_name,
                serialized_len = serialized.len(),
                serialized = %serialized,
                "Serialized tool output ({} chars)",
                serialized.len()
            );
            Ok(serialized)
        }
        Ok(Err(e)) => {
            error!(
                tool = %tool_name,
                elapsed_ms = exec_elapsed.as_millis(),
                error = %e,
                "❌ Tool execution failed: {}",
                e
            );
            Err(format!("Tool execution failed: {}", e))
        }
        Err(_) => {
            error!(
                tool = %tool_name,
                timeout_secs = 30,
                "⏰ Tool timed out after {}s",
                30
            );
            Err(format!(
                "Tool '{}' timed out after {:?}",
                tool_name, timeout
            ))
        }
    }
}

/// Process a tool result into a ChatMessage.
pub fn process_tool_result(
    tool_name: &str,
    tool_call_id: &str,
    result: &Result<String, String>,
) -> ChatMessage {
    let content = match result {
        Ok(output) => {
            let wrapped = format!("<tool_output>{}</tool_output>", output);
            debug!(
                tool = %tool_name,
                tool_call_id = %tool_call_id,
                content_len = wrapped.len(),
                "Wrapping tool output in <tool_output> tags ({} chars)",
                wrapped.len()
            );
            trace!(
                tool = %tool_name,
                wrapped_content = %wrapped,
                "Full wrapped tool result"
            );
            wrapped
        }
        Err(e) => {
            let error_content = format!("Error: {}", e);
            warn!(
                tool = %tool_name,
                tool_call_id = %tool_call_id,
                error = %e,
                "Creating error tool result message"
            );
            error_content
        }
    };
    info!(
        tool = %tool_name,
        tool_call_id = %tool_call_id,
        is_error = result.is_err(),
        "📝 Creating tool result ChatMessage (role=Tool)"
    );
    ChatMessage::tool_result(tool_call_id, tool_name, content)
}
